apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sfeir-hivemind
  annotations: {}
spec:
  template:
    metadata:
      annotations: {}
    spec:
      containers:
        - env: []
          image: europe-docker.pkg.dev/shikanime-studio/sfeir-hivemind-containers/sfeir-hivemind
          name: bento
          resources:
            limits:
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
          startupProbe:
            httpGet:
              path: /readyz
              port: 8080
          timeoutSeconds: 600
