apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sfeir-hivemind
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containers:
        - env: []
          image: europe-west1-docker.pkg.dev/shikanime-studio/sfeir-hivemind/sfeir-hivemind
          name: bento
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
          startupProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 60
          volumeMounts:
            - mountPath: /home/bentoml/.cache/torch
              name: torch-cache
      serviceAccountName: sfeir-hivemind@shikanime-studio.iam.gserviceaccount.com
      timeoutSeconds: 600
      volumes:
        - name: torch-cache
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
