apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sfeir-hivemind
build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/shikanime-studio/sfeir-hivemind/sfeir-hivemind
      custom:
        buildCommand: |
          if [ -z "$PUSH_IMAGE" ]; then
            python -m sfeir.hivemind.build -t $IMAGE
          else
            python -m sfeir.hivemind.build -t $IMAGE --push
          fi
        dependencies:
          paths:
            - sfeir/hivemind
            - pyproject.toml
  local:
    useBuildkit: true
profiles:
  - name: shikanime-studio
    manifests:
      kustomize:
        paths:
          - manifests/overlays/default
    deploy:
      cloudrun:
        projectid: shikanime-studio
        region: europe-west1
