apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sfeir-hivemind
build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/shikanime-studio/sfeir-hivemind/sfeir-hivemind
      custom:
        buildCommand: |
          if [ -z "$PUSH_IMAGE" ]; then
            python -m sfeir.hivemind.build -t $IMAGE
          else
            python -m sfeir.hivemind.build -t $IMAGE --push
          fi
        dependencies:
          paths:
            - sfeir/hivemind
            - sfeir/langchain
            - pyproject.toml
  local:
    useBuildkit: true
