apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sfeir-hivemind
build:
  artifacts:
    - image: europe-docker.pkg.dev/shikanime-studio/sfeir-hivemind-containers/sfeir-hivemind
      custom:
        buildCommand: |
          python -m sfeir.hivemind.build \
            -t europe-docker.pkg.dev/shikanime-studio/sfeir-hivemind-containers/sfeir-hivemind
  local:
    useBuildkit: true
profiles:
  - name: shikanime-studio
    manifests:
      kustomize:
        paths:
          - manifests/overlays/default
    deploy:
      cloudrun:
        projectid: shikanime-studio
        region: europe-west1
