# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sfeir/hivemind/protos/hivemind.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$sfeir/hivemind/protos/hivemind.proto\x12\x15sfeir.hivemind.protos"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2_\n\x07Greeter\x12T\n\x08SayHello\x12#.sfeir.hivemind.protos.HelloRequest\x1a!.sfeir.hivemind.protos.HelloReply"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "sfeir.hivemind.protos.hivemind_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _HELLOREQUEST._serialized_start = 63
    _HELLOREQUEST._serialized_end = 91
    _HELLOREPLY._serialized_start = 93
    _HELLOREPLY._serialized_end = 122
    _GREETER._serialized_start = 124
    _GREETER._serialized_end = 219
# @@protoc_insertion_point(module_scope)
