apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: service.patch.yaml
    target:
      group: serving.knative.dev
      version: v1
      kind: Service
      name: sfeir-hivemind
