- op: add
  path: /spec/template/metadata/annotations/autoscaling.knative.dev~1maxScale
  value: "3"
- op: add
  path: /spec/template/metadata/annotations/run.googleapis.com~1startup-cpu-boost
  value: "true"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DEEP_LAKE_DATASET_URI
    value: "gcs://shikanime-studio-hivemind-deep-lake-dataset/books/"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: VERTEX_AI_PROJECT
    value: "shikanime-studio"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: VERTEX_AI_LOCATION
    value: "us-central1"
