name: Continuous Integration

on:
  push:
    branches:
      - refactor/bento-models-model-extract-limit-testing

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: |
          pip install -e .
          pip install -e ".[quantization]"
      - run: skaffold build -p github-infinity-blackhole
